alter table WFSTP_SCREEN_ACTION_TEMPLATE add column AVAILABLE_IN_EXTERNAL_SYSTEM boolean ;
alter table WFSTP_SCREEN_ACTION_TEMPLATE add column EXTERNAL_SCRIPT text ;
alter table WFSTP_SCREEN_ACTION_TEMPLATE add column EXTERNAL_PERMIT_SCRIPT text ;
